SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

UPDATE `pfleet`.`deductions` SET `source_id`=null WHERE `source_id`=1;

UPDATE `pfleet`.`payments` SET `source_id`=null WHERE `source_id`=1;

TRUNCATE TABLE `pfleet`.`file_storage`;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
