ALTER TABLE powerunit
    ADD COLUMN vin VARCHAR(50) NULL DEFAULT NULL AFTER code,
    ADD COLUMN tractor_year SMALLINT(4) NULL DEFAULT NULL AFTER vin,
    ADD COLUMN license VARCHAR(50) NULL DEFAULT NULL AFTER tractor_year,
    ADD COLUMN license_state  VARCHAR(50) NULL DEFAULT NULL AFTER license;

ALTER TABLE powerunit_temp
    ADD COLUMN vin VARCHAR(50) NULL DEFAULT NULL AFTER code,
    ADD COLUMN tractor_year VARCHAR(50) NULL DEFAULT NULL AFTER vin,
    ADD COLUMN license VARCHAR(50) NULL DEFAULT NULL AFTER tractor_year,
    ADD COLUMN license_state  VARCHAR(50) NULL DEFAULT NULL AFTER license;
