ALTER TABLE `contractor_temp`
 ADD COLUMN  `middle_initial` VARCHAR (255) NULL DEFAULT NULL,
 ADD COLUMN  `gender_id` VARCHAR (255) NULL DEFAULT NULL,
 ADD COLUMN  `status` VARCHAR (255) NULL DEFAULT NULL,
 ADD COLUMN  `start_date` VARCHAR (255) NULL DEFAULT NULL,
 ADD COLUMN  `termination_date` VARCHAR (255) NULL DEFAULT NULL,
 ADD COLUMN  `rehire_date` VARCHAR (255) NULL DEFAULT NULL
;

ALTER TABLE `contractor`
 ADD COLUMN  `middle_initial` VARCHAR (255) NULL DEFAULT NULL
;