<?php $title = 'Reserve Transactions' ?>
<?php $this->headTitle()->append($title) ?>
    <h3><?php echo $title ?></h3>
<?php echo $this->grid() ?>

<?php if (isset($this->allRAGrid) && isset($this->maintenanceRAGrid) && isset($this->powerUnitsGrid)): ?>
<?php echo $this->partial(
        'popup_transaction.phtml',
    array(
        'gridTitle' => 'Select desired Power Unit(s) and Reserve Account(s) to create new contribution(s)',
        'tabTitle' => 'Reserve Accounts',
        'selector' => 'contribution',
        'type' => Application_Model_Entity_System_ReserveTransactionTypes::CONTRIBUTION,
        'grids' => array(),
        'cyclePeriods' => $this->activeCyclePeriods,
        'reserveAccountsGrid' => $this->allRAGrid,
        'powerUnitsGrid' => $this->powerUnitsGrid
    )
) ?>

<?php echo $this->partial(
        'popup_transaction.phtml',
    array(
        'gridTitle' => 'Select desired Power Unit(s) and Reserve Account(s) to create new withdrawal(s)',
        'tabTitle' => 'Reserve Accounts',
        'type' => Application_Model_Entity_System_ReserveTransactionTypes::WITHDRAWAL,
        'selector' => 'withdrawal',
        'grids' => array(),
        'cyclePeriods' => $this->activeCyclePeriods,
        'reserveAccountsGrid' => $this->maintenanceRAGrid,
        'powerUnitsGrid' => $this->powerUnitsGrid
    )
) ?>
<?php endif ?>
