<?php
use AcceptanceTester\LoggedUserSteps;
use Codeception\Module\Deduction_Data;
use Codeception\Module\BaseSelectors;

$I=new LoggedUserSteps($scenario);
$scenario->group('UI');
$Base = new BaseFunctionsPage($I);
$I->wantTo('see UI elements on Create Master Deduction Templates page');
$I->click(Deduction_Data::$deductions_Menu); //click on Deductions menu
$I->click(Deduction_Data::$create_Master_Deduction_Template_Submenu); //click on Create Master Deduction Templates submenu
$I->seeInCurrentUrl(Deduction_Data::$create_Master_Deduction_Templates_Menu_Link);
$I->see(Deduction_Data::$master_deduction_template_Details,BaseSelectors::$page_Header);
$I->see(Deduction_Data::$vendor);
$I->seeElement(Deduction_Data::$vendor_Locator);
$I->click(Deduction_Data::$vendor_Locator);
$I->waitForElementVisible(Deduction_Data::$select_Provider_Popup);
$I->seeElement(Deduction_Data::$select_Provider_Popup);
$I->see(Deduction_Data::$title_Select_Provider_Popup,BaseSelectors::$page_Header);
$I->click(Deduction_Data::$customers_Tab_In_Popup);
$table=$Base->getTextElement(Deduction_Data::$customer_Header_Table_In_Popup);
$Base->checkArrayDiff($table,Deduction_Data::$customer_Header_Table_In_Popup_Original);
$I->click(Deduction_Data::$vendor_Tab_In_Popup);
$table=$Base->getTextElement(Deduction_Data::$vendors_Header_Table_In_Popup);
$Base->checkArrayDiff($table,Deduction_Data::$vendors_Header_Table_In_Poup_Original);
$I->seeElement(Deduction_Data::$close_Button_Select_Provide_Popup);
$I->click(Deduction_Data::$close_Button_Select_Provide_Popup);
$I->see(Deduction_Data::$deduction_Code);
$I->seeElement(Deduction_Data::$deduction_Code_Locator);
$I->see(Deduction_Data::$description);
$I->seeElement(Deduction_Data::$description_Locator);
$I->see(Deduction_Data::$category);
$I->seeElement(Deduction_Data::$category_Locator);
$I->see(Deduction_Data::$department);
$I->seeElement(Deduction_Data::$department_Locator);
$I->see(Deduction_Data::$GL_Code);
$I->seeElement(Deduction_Data::$GL_Code_Locator);
$I->see(Deduction_Data::$disbursement_Code);
$I->seeElement(Deduction_Data::$disbursement_Code_Locator);
$I->see(Deduction_Data::$quantity);
$I->seeElement(Deduction_Data::$quantity_Locator);
$I->see(Deduction_Data::$rate);
$I->seeElement(Deduction_Data::$rate_Locator);
$I->see(Deduction_Data::$recurring);
$I->seeElement(Deduction_Data::$recurring_Locator);
$I->checkOption(Deduction_Data::$recurring_Locator);
$Base->checkFrequencyElement();
$I->see(Deduction_Data::$eligible);
$I->seeElement(Deduction_Data::$eligible_Locator);
$I->checkOption(Deduction_Data::$eligible_Locator);
$I->seeOptionIsSelected(Deduction_Data::$eligible_Locator,Deduction_Data::$eligible);
$I->see(Deduction_Data::$reserve_Account);
$I->seeElement(Deduction_Data::$reserve_Account_Field_locator);
$I->click(Deduction_Data::$reserve_Account_Field_locator);
$I->waitForElementVisible(Deduction_Data::$select_Reserve_Account_Popup);
$I->seeElement(Deduction_Data::$select_Reserve_Account_Popup);
$I->see(Deduction_Data::$title_Select_Reserve_Account_Popup, BaseSelectors::$page_Header);
$table=$Base->getTextElement(Deduction_Data::$select_Reserve_Account_Header_Table_In_popup);
$Base->checkArrayDiff($table,Deduction_Data::$select_Reserve_Account_Header_Table_In_popup_Original);
$I->seeElement(Deduction_Data::$close_Button_Select_Reserve_Account_Popup);
$I->click(Deduction_Data::$close_Button_Select_Reserve_Account_Popup);
