<?php $this->headTitle()->append($this->title); ?>

<h3>
    <?php echo $this->title ?>
</h3>
<br/>

<form  action="<?php echo $this->escape($this->form->getAction()); ?>"
       method="<?php echo $this->escape($this->form->getMethod()); ?>"
       name="<?php echo $this->escape($this->form->getName()) ?>"
       class="form-horizontal">
    <fieldset>
        <?php echo $this->form->id ?>
        <?php echo $this->form->carrier_id ?>

        <?php echo $this->form->cycle_period_id ?>
        <?php echo $this->form->cycle_start_date ?>
        <?php echo $this->form->cycle_close_date ?>

        <?php echo $this->form->processing_date?>
        <?php echo $this->form->disbursement_date?>
        <div id="change-cycle-rule-fields" class="<?php if (!$this->form->first_start_day->getErrors() && !$this->form->second_start_day->getErrors() && !$this->form->week_day->getErrors()) echo 'nondisplay' ?>">
            <div id="semi-monthly-fields" class="<?php if (!in_array((int)$this->form->cycle_period_id->getValue(), array(Application_Model_Entity_System_CyclePeriod::SEMY_MONTHLY_PERIOD_ID, Application_Model_Entity_System_CyclePeriod::MONTHLY_SEMI_MONTHLY_ID)) && !$this->form->first_start_day->getErrors() && !$this->form->second_start_day->getErrors()) echo 'nondisplay'?>">
                <?php echo $this->form->first_start_day ?>
                <div id="second_start_day_wrapper">
                    <?php echo $this->form->second_start_day ?>
                </div>
            </div>
            <div id="week_day_wrapper" class="<?php if (in_array((int)$this->form->cycle_period_id->getValue(), array(Application_Model_Entity_System_CyclePeriod::MONTHLY_PERIOD_ID, Application_Model_Entity_System_CyclePeriod::SEMY_MONTHLY_PERIOD_ID, Application_Model_Entity_System_CyclePeriod::MONTHLY_SEMI_MONTHLY_ID)) && !$this->form->week_day->getErrors()) echo 'nondisplay' ?>">
                <?php echo $this->form->week_day ?>
                <div id="second_week_day_wrapper">
                    <?php echo $this->form->second_week_day ?>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>

        <div class="clearfix"></div>
        <?php echo $this->form->cycle_status ?>
        <div class="form-actions">
            <?php if (isset($this->form->submit)): ?>
                <input type="submit" name="submit" id="submit" value="Save" class="btn btn-primary">
            <?php endif ?>
            <a class="btn cancel btn-danger">Cancel</a>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
$(function() {
    $("input[name='disbursement_date'], input[name='processing_date']").datepicker();
    <?php if (Application_Model_Entity_Accounts_User::getCurrentUser()->isAdmin()): ?>
    $("input[name='cycle_start_date'], input[name='cycle_close_date']").datepicker();
    <?php endif ?>
});
</script>