<?php if (is_array($this->data)): ?>
<tr class="totals not-sortable-item">
    <?php if (!$this->gridData['hideCheckbox']) : ?>
        <td></td>
    <?php endif ?>
    <td colspan="6">Total</td>
    <td class="num"><?php echo $this->money($this->data['total_original_amount']) ?></td>
    <td class="num"><?php echo $this->money($this->data['total_transaction_fee']) ?></td>
    <td class="num"><?php echo $this->money($this->data['total_paid']) ?></td>
    <td class="num"><?php echo $this->money($this->data['total_balance']) ?></td>
    <td></td>
</tr>
<?php endif ?>
