<?php $this->headTitle()->append($this->title); ?>
<h3>
    <?php echo $this->title; ?>
</h3>

<div class="row">
    <form class="form-horizontal hide-buttons" action="<?php echo $this->escape($this->form->getAction()) ?>"
        method="<?php echo $this->escape($this->form->getMethod()) ?>"
        name="<?php echo $this->escape($this->form->getName()) ?>">
        <div class="span6">
            <fieldset>
                <?php echo $this->form->payment_code ?>
                <?php echo $this->form->contractor_name ?>
                <?php echo $this->form->contractor_code ?>
                <?php echo $this->form->powerunit_code ?>
                <?php echo $this->form->carrier_payment_code ?>
                <?php echo $this->form->description ?>
                <?php echo $this->form->category ?>
                <?php echo $this->form->department ?>
                <?php echo $this->form->driver ?>
                <?php echo $this->form->reference ?>
                <?php echo $this->form->loaded_miles ?>
                <?php echo $this->form->empty_miles ?>
                <?php echo $this->form->origin_city ?>
                <?php echo $this->form->destination_city ?>
                <?php echo $this->form->shipment ?>
                <?php echo $this->form->shipment_complete_date ?>
                <?php echo $this->form->gl_code ?>
                <!--                -->
                <?php //echo $this->form->invoice_due_date ?>
                <!--                -->
                <?php //echo $this->form->terms ?>

                <?php if ($this->cycle->getStatusId() < Application_Model_Entity_System_SettlementCycleStatus::APPROVED_STATUS_ID): ?>
                            <div class="form-actions">
                                <?php if (isset($this->form->submit)): ?>
                                    <input type="submit" name="submit" id="submit" value="Save" class="btn btn-primary">
                                <?php endif ?>
                                <a class="btn cancel btn-danger">Cancel</a>
                            </div>
                <?php endif ?>
            </fieldset>
        </div>
        <div class="span6">
            <fieldset>
                <?php echo $this->form->invoice ?>
                <?php echo $this->form->invoice_date ?>
                <?php echo $this->form->disbursement_code ?>
                <?php echo $this->form->disbursement_date ?>
                <?php echo $this->form->settlement_cycle_id ?>
                <?php echo $this->form->quantity ?>
                <?php echo $this->form->rate ?>
                <?php echo $this->form->taxable ?>
                <?php echo $this->form->amount ?>
                <div id="change-cycle-rule-fields" class="<?php if (!$this->form->recurring->getValue() && !$this->form->first_start_day->getErrors() && !$this->form->second_start_day->getErrors() && !$this->form->week_day->getErrors())
                    echo 'nondisplay' ?>">
                    <?php echo $this->form->billing_cycle_id ?>
                    <div id="semi-monthly-fields" class="<?php if (!in_array((int) $this->form->billing_cycle_id->getValue(), array(Application_Model_Entity_System_CyclePeriod::MONTHLY_PERIOD_ID, Application_Model_Entity_System_CyclePeriod::SEMY_MONTHLY_PERIOD_ID, Application_Model_Entity_System_CyclePeriod::MONTHLY_SEMI_MONTHLY_ID)) && !$this->form->first_start_day->getErrors() && !$this->form->second_start_day->getErrors())
                        echo 'nondisplay' ?>">
                        <?php echo $this->form->first_start_day ?>
                        <div id="second_start_day_wrapper" class="<?php if (!in_array((int) $this->form->billing_cycle_id->getValue(), array(Application_Model_Entity_System_CyclePeriod::SEMY_MONTHLY_PERIOD_ID, Application_Model_Entity_System_CyclePeriod::MONTHLY_SEMI_MONTHLY_ID)) && !$this->form->second_start_day->getErrors())
                            echo 'nondisplay' ?>">
                            <?php echo $this->form->second_start_day ?>
                        </div>
                    </div>
                    <div id="week_offset_wrapper" class="<?php if (!$this->form->week_offset->getErrors())
                        echo 'nondisplay' ?>">
                        <?php echo $this->form->week_offset ?>
                    </div>
                    <div id="week_day_wrapper" class="<?php if (in_array((int) $this->form->billing_cycle_id->getValue(), array(Application_Model_Entity_System_CyclePeriod::MONTHLY_PERIOD_ID, Application_Model_Entity_System_CyclePeriod::SEMY_MONTHLY_PERIOD_ID, Application_Model_Entity_System_CyclePeriod::MONTHLY_SEMI_MONTHLY_ID)) && !$this->form->week_day->getErrors())
                        echo 'nondisplay' ?>">
                        <?php echo $this->form->week_day ?>
                        <div id="second_week_day_wrapper" class="<?php if ($this->form->billing_cycle_id->getValue() != Application_Model_Entity_System_CyclePeriod::SEMI_WEEKLY_PERIOD_ID && !$this->form->second_week_day->getErrors())
                            echo 'nondisplay' ?>">
                            <?php echo $this->form->second_week_day ?>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <?php echo $this->form->approved_datetime ?>
                <?php echo $this->form->approved_by_name ?>
                <?php echo $this->form->created_datetime ?>
                <?php echo $this->form->created_by_name ?>
                <?php echo $this->form->source_id ?>
                <?php echo $this->form->carrier_id ?>
                <?php echo $this->form->approved_by ?>
                <?php echo $this->form->created_by ?>
                <?php echo $this->form->id ?>
                <?php echo $this->form->status ?>
                <?php echo $this->form->setup_id ?>
                <?php echo $this->form->contractor_id ?>
                <?php echo $this->form->status_name ?>
                <?php echo $this->form->priority ?>
            </fieldset>
        </div>
    </form>
</div>
