<?php $data = $this->contractor ?>
<tr class="totals not-sortable-item">
    <?php if (Application_Model_Entity_Accounts_User::getCurrentUser()->getCurrentCycle()->getStatusId() != Application_Model_Entity_System_SettlementCycleStatus::APPROVED_STATUS_ID) : ?>
        <td></td>
    <?php endif ?>
    <td colspan="7">Total</td>
    <td class="num">-
        <?php echo $this->money($data['deductions_amount']) ?>
    </td>
    <td class="num">
        <?php echo $this->money($data['deductions_balance']) ?>
    </td>
    <td class="num">
        <?php echo $this->money($data['deductions_adjusted_balance']) ?>
    </td>
    <td colspan="2"></td>
</tr>
