<br/>
<?php $callbacks = $this->callbacks ?>
<div id="<?php echo $this->destFieldName; ?>_modal" class="modal hide fade in multiselect filterable setup multigrid user-entity-modal" data-dest-field="<?php echo $this->destFieldName; ?>">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">X</button>
        <h3><?php echo $this->gridTitle; ?></h3>
    </div>
    <div class="modal-body">
        <ul class="nav nav-tabs" id="<?php echo $this->destFieldName; ?>_tab">
            <?php foreach($this->grids as $tabTitle => $grid ): ?>
                <li><a href="#<?php echo $tabTitle; ?>"><?php echo $tabTitle; ?></a></li>
                <?php $firstTab = false; ?>
            <?php endforeach; ?>
        </ul>
        <div class="tab-content">
            <?php foreach($this->grids as $tabTitle => $grid ): ?>
                <div class="tab-pane" id="<?php echo $tabTitle; ?>">
                    <?php echo $this->grid()->render($grid); ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="modal-footer">

    </div>
</div>