<?php $this->headTitle()->append($this->title); ?>
<h3><?php echo $this->title ?></h3><br/>
<form action="<?php echo $this->escape($this->form->getAction()); ?>"
      method="<?php echo $this->escape($this->form->getMethod()); ?>"
      name="<?php echo $this->escape($this->form->getName()); ?>"
      class="form-horizontal permissions">
    <?php echo $this->form->id; ?>
    <?php echo $this->form->user_id; ?>
    <div class="row">
        <?php
        if ($this->form instanceof Application_Form_Entity_ManagerPermissions) {
            echo $this->partial('users/index/permissions-manager.phtml', ['form' => $this->form]);
        } elseif ($this->form instanceof Application_Form_Entity_SpecialistPermissions) {
            echo $this->partial('users/index/permissions-specialist.phtml', ['form' => $this->form]);
        } elseif ($this->form instanceof Application_Form_Entity_OnboardingPermissions) {
            echo $this->partial('users/index/permissions-onboarding.phtml', ['form' => $this->form]);
        }
        ?>
    </div>
        <div class="row">
            <div class="pull-left">
                <?php echo $this->form->submit; ?>
            </div>
            <a class="btn cancel btn-danger">Cancel</a>
        </div>
</form>
