<div class="span">
    <dl>
        <dt><h3>Reserves <input type="checkbox" class="check-all pull-right"></h3></dt>
        <dd><?php echo $this->form->reserve_transaction_vendor_view; ?></dd>
        <dd><?php echo $this->form->reserve_account_contractor_view; ?></dd>
        <dd><?php echo $this->form->reserve_account_vendor_view; ?></dd>
        <dd><?php echo $this->form->reserve_account_vendor_manage; ?></dd>
    </dl>
</div>
<div class="span">
    <dl>
        <dt><h3>Vendor <input type="checkbox" class="check-all pull-right"></h3></dt>
        <dd><?php echo $this->form->vendor_view; ?></dd>
        <dd><?php echo $this->form->vendor_manage; ?></dd>
    </dl>
</div>
<div class="span">
    <dl>
        <dt><h3>Deduction <input type="checkbox" class="check-all pull-right"></h3></dt>
        <dd><?php echo $this->form->vendor_deduction_manage; ?></dd>
        <dd><?php echo $this->form->template_view; ?></dd>
        <dd><?php echo $this->form->template_manage; ?></dd>
        <dd><?php echo $this->form->uploading; ?></dd>
    </dl>
</div>
<div class="span">
    <dl>
        <dt><h3>Reporting <input type="checkbox" class="check-all pull-right"></h3></dt>
        <dd><?php echo $this->form->reporting_deduction_remittance_file; ?></dd>
        <dd><?php echo $this->form->reporting_general; ?></dd>
    </dl>
</div>
