<?php if($this->isEdit): ?>
    <h3>Edit Powerunit</h3><br />
    <div class="left bank-reserve-acc-actions">
        <a class="btn btn-danger confirm pull-right" confirm-type="Deletion" href="<?php echo $this->url(array('action' => 'delete', 'controller' => 'powerunits_index', 'id' => $this->powerunit->getId()), null, true)?>"><i class="icon-trash icon-white"></i> Delete Powerunit</a>
    </div>
<?php else: ?>
    <h3>Create Powerunit</h3><br />
<?php endif ?>

<form action="<?php echo $this->escape($this->form->getAction()); ?>"
      method="<?php echo $this->escape($this->form->getMethod()); ?>"
      name="<?php echo $this->escape($this->form->getName()); ?>"
      class="form-horizontal<?php echo ($this->form->id->getValue()) ? ' hide-buttons' : ''; ?>"
>
    <?php echo $this->form->id ?>
    <?php echo $this->form->code; ?>
    <?php echo $this->form->contractor_id; ?>
    <?php echo $this->form->contractor_code; ?>
    <?php echo $this->form->contractor_name; ?>
    <?php echo $this->form->start_date; ?>
    <?php echo $this->form->termination_date; ?>
    <?php echo $this->form->status; ?>
    <?php echo $this->form->domicile; ?>
    <?php echo $this->form->plate_owner; ?>
    <?php echo $this->form->form2290; ?>
    <?php echo $this->form->ifta_filing_owner; ?>
    <?php echo $this->form->vin; ?>
    <?php echo $this->form->tractor_year; ?>
    <?php echo $this->form->license; ?>
    <?php echo $this->form->license_state; ?>

    <div class="form-actions">
        <?php if (isset($this->form->submit)) { ?>
            <input type="submit" name="submit" id="submit" value="Save" class="btn btn-primary">
        <?php } ?>
        <a class="btn cancel btn-danger" <?php echo $this->cancelUrl; ?>>Cancel</a>
    </div>
    <?php echo $this->form->carrierId; ?>
</form>


<div id="confirm-modal" class="modal hide fade in">
    <div class="modal-header">
        <a class="btn close" data-dismiss="modal">X</a>
        <h3>Confirm <span class="confirm-type"></span> of Records</h3>
    </div>
    <div class="modal-body">
        <p class="confirm-description"><span class="confirm-type"></span> these records is irreversible.</p>
        <p>Do you want to proceed?</p>
    </div>
    <div class="modal-footer">
        <a href="" class="btn btn-danger" id="btn-confirm">Yes</a>
        <a data-dismiss="modal" class="btn btn-success">No</a>
    </div>
</div>
<?php $this->inlineScript()->appendFile($this->baseUrl() . '/js/powerunit-page.js') ?>
<script>
    contractors = <?php echo json_encode($this->form->contractors)?>;
</script>
