<h3 class='report-title'><?php echo $this->reportTitle ?></h3><br />
<table class="datagrid table table-bordered table-striped report-grid">
    <thead>
        <tr>
            <th>Header1</th>
            <th>Header2</th>
            <th>Header3</th>
            <th>Header4</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Data1</td>
            <td>Data2</td>
            <td>Data3</td>
            <td>Data4</td>
        </tr>
        <tr>
            <td>Data21</td>
            <td>Data22</td>
            <td>Data23</td>
            <td>Data24</td>
        </tr>
    </tbody>
</table>