<table class="report-grid" topntail repeat_header="1">
    <thead>
        <tr class="report-title">
            <th colspan="15" class="text-center bottom-line">Compensation History</th>
        </tr>
        <tr class="info-row"><th colspan="15"></th></tr>
        <?php if ($this->gridData['form']['date_filter_type'] == Application_Model_Report_Reporting::INVOICE_DATE): ?>
            <tr class="info-row">
                <th class="info-title">View By:</th>
                <th class="info-value" colspan="14" style="font-weight: normal">Invoice Date</th>
            </tr>
            <tr class="info-row">
                <th class="info-title">Range:</th>
                <th class="info-value" colspan="14" style="font-weight: normal"><?php echo \DateTime::createFromFormat('m/d/Y', $this->gridData['form']['invoice_start_date'])->format('m/d/y') . ' - ' . \DateTime::createFromFormat('m/d/Y', $this->gridData['form']['invoice_end_date'])->format('m/d/y') ?></th>
            </tr>
        <?php else: ?>
            <?php
            $startCycle = Application_Model_Entity_Settlement_Cycle::staticLoad($this->gridData['form']['starting_period']);
            $startCycle->changeDateFormat(array('cycle_start_date'), true, true);
            $endCycle = Application_Model_Entity_Settlement_Cycle::staticLoad($this->gridData['form']['ending_period']);
            $endCycle->changeDateFormat(array('cycle_close_date'), true, true);
            ?>
            <tr class="info-row">
                <th class="info-title">View By:</th>
                <th class="info-value" colspan="14" style="font-weight: normal">Settlement Cycle</th>
            </tr>
            <tr class="info-row">
                <th class="info-title">Range:</th>
                <th class="info-value" colspan="14" style="font-weight: normal"><?php echo $startCycle->getCycleStartDate() . ' - ' . $endCycle->getCycleCloseDate() ?></th>
            </tr>
        <?php endif ?>
        <tr class="info-row"><th colspan="15"></th></tr>
        <tr class="subtable">
            <?php foreach($this->gridData['fields'] as $name => $title): ?>
                <th class="field-name-<?php echo $name ?>"><?php echo $title ?></th>
            <?php endforeach ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->gridData['contractors'] as $contractor): ?>
            <?php foreach($contractor['payments'] as $payment): ?>
            <tr>
                <?php foreach($this->gridData['fields'] as $key => $title): ?>
                    <?php $method = 'get' . Application_Model_Base_Object::uc_words($key, '') ?>
                    <?php if (isset($this->gridData['callbacks'][$key])): ?>
                        <?php $callback = $this->gridData['callbacks'][$key]?>
                    <td <?php echo $callback::getInstance()->renderWrapper($payment->getData(), $payment->$method(), $this, array('forReport' => true)) ?>><div><?php echo $callback::getInstance()->render($payment->getData(), $payment->$method(), $this, array('forReport' => true)) ?></div></td>
                    <?php else: ?>
                    <td><?php echo $payment->$method() ?></td>
                    <?php endif ?>
                <?php endforeach ?>
            </tr>
            <?php endforeach ?>
            <tr>
                <td colspan="11" class="text-right  bold-text">Total:</td>
                <td class="top-line num  bold-text"><?php echo number_format($contractor['total_quantity'], 1) ?></td>
                <td colspan="2" class="top-line num  bold-text"><?php echo '<span class="pull-left">$</span>' . number_format($contractor['total_amount'], 2) ?></td>
                <td></td>
            </tr>
            <tr class="info-row"><th colspan="15"></th></tr>
        <?php endforeach ?>
        <tr>
            <?php if (count($this->gridData['contractors']) > 1): ?>
            <td colspan="11" class="text-right  bold-text" style="font-weight: bold">Grand Total:</td>
            <td class="top-line num bold-text" style="font-weight: bold"><?php echo number_format($this->gridData['grand_total_quantity'], 1) ?></td>
            <td colspan="2" class="top-line num  bold-text"><?php echo '<span class="pull-left">$</span>' . number_format($this->gridData['grand_total_amount'], 2) ?></td>
            <td></td>
            <?php elseif (count($this->gridData['contractors']) == 0): ?>
                <td colspan="15" class="text-center ">Nothing to show!</td>
            <?php endif ?>
        </tr>
        <tr class="info-row"><td colspan="15"></td></tr>
    </tbody>
</table>