<?php
$buttons = [
    'payment-setup'=> $this->url(array('controller' => 'payments_payments', 'action' => 'new')),
    'deduction-setup'=> $this->url(array('controller' => 'deductions_deductions', 'action' => 'new')),
    'contribution'=> $this->url(array('controller' => 'reserve_transactions', 'action' => 'new', 'type' => Application_Model_Entity_System_ReserveTransactionTypes::CONTRIBUTION)),
    'withdrawal'=> $this->url(array('controller' => 'reserve_transactions', 'action' => 'new', 'type' => Application_Model_Entity_System_ReserveTransactionTypes::WITHDRAWAL)),
];

?>
<div class="<?php echo $this->selector ?> setup popup_checkbox_modal modal hide fade in" data-entity="<?php echo $this->setupGrid->getEntityName() ?>" data-contractor="<?php echo $this->contractorId ?>">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">X</button>
        <h3><?php echo $this->gridTitle; ?></h3>
    </div>
    <div class="modal-body">
        <div><?php echo $this->grid()->render($this->setupGrid) ?></div>
    </div>
    <div class="modal-footer">
        <div class="pull-left">
            Period:
            <input class="settlement-cycle-data span2" type="text" readonly="readonly" value="<?php echo $this->cycle->getCyclePeriodString() ?>" data-cycle-id="<?php echo $this->cycle->getId() ?>">
        </div>
        <?php if (isset($this->showInvoiceDateSelector) && $this->showInvoiceDateSelector = true): ?>
            <div class="span pull-left">
                Invoice Date:

                <input class="invoice-date span2" type="text" placeholder="If empty - set automatically">
            </div>
        <?php endif ?>
        <a  class="btn btn-success addSelectedItems"
           data-target-url="<?php echo $buttons[$this->selector] . '?back=' . urlencode('settlement_index/contractor/id/' . Zend_Controller_Front::getInstance()->getRequest()->getParam('id')); ?>"><i class="icon-ok icon-white"></i> Add
        </a>
    </div>
</div>
