<div class="alert alert-block alert-error">
    <a class="close" data-dismiss="alert" href="#">×</a>
    <h2 class="alert-heading"><?php echo $this->title; ?></h2>
    <h4>Message:</h4><pre><?php echo $this->message ?></pre>
    <h4>Code:</h4><pre><?php echo $this->code ?></pre>
    <h4>Stack trace:</h4><pre><?php echo $this->stackTrace ?></pre>
    <h4>Request:</h4><pre><?php echo $this->request ?></pre>
</div>
