<?php $cycle = $this->cycle ?>
<table class="datagrid table table-bordered  additional-cycle-grid">
    <thead>
    <tr class="header">
        <th>Settlement Cycle</th>
        <th>Period Start Date</th>
        <th>Period Close Date</th>
        <th>Processing Date</th>
        <th>Disbursement Date</th>
        <th>Disbursement Status</th>
        <th name="action">Action</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <?php if (!$cycle->getId()): ?>
            <td class="placeholder" colspan="8" style="text-align: center">Cycle not exist!</td>
        <?php else: ?>
        <td><?php echo $cycle->getCyclePeriod()->getTitle() ?></td>
        <td><?php echo $this->date($cycle->getCycleStartDate()) ?></td>
        <td><?php echo $this->date($cycle->getCycleCloseDate()) ?></td>
        <td><?php echo $this->date($cycle->getProcessingDate()) ?></td>
        <td><?php echo $this->date($cycle->getDisbursementDate()) ?></td>
        <td><?php echo $cycle->getDisbursementStatusTitle() ?></td>

        <?php if ($cycle->getDisbursementStatus() != Application_Model_Entity_System_PaymentStatus::APPROVED_STATUS
                  && $cycle->getStatusId() == Application_Model_Entity_System_SettlementCycleStatus::APPROVED_STATUS_ID
                  && Application_Model_Entity_Accounts_User::getCurrentUser()->hasPermission(Application_Model_Entity_Entity_Permissions::DISBURSEMENT_APPROVE)): ?>
            <td class="buttons">
                <div>
                    <?php if ($errors = $this->cycle->getDisbursementErrors()) : ?>
                        <?php echo $this->setButtons(array('approve-disabled'), $cycle->getId(), array('controller' => 'transactions_disbursement'));
                        echo $this->partial(
                        'partials/disbursement/validation.phtml', array(
                        'errors' => $errors
                        )); ?>
                    <?php else: ?>
                    <?php echo $this->setButtons(array('approve'), $cycle->getId(), array('controller' => 'transactions_disbursement')); ?>
                    <?php endif ?>
                </div>
            </td>
        <?php else : ?>
            <td class="buttons none-label">
                <div>
                    None
                </div>
            </td>
        <?php endif ?>
        <?php endif ?>
    </tr>
    </tbody>
</table>
