<?php $this->headTitle()->append($this->title); ?>
    <?php if($entityId = $this->form->entity_id->getValue()): ?>
        <?php
        $vendor = new Application_Model_Entity_Entity_Vendor();
        $vendor->load($entityId, 'entity_id');
        ?>
    <h3>Edit Vendor</h3><br />
    <div class="left bank-reserve-acc-actions">
        <?php if (Application_Model_Entity_Accounts_User::getCurrentUser()->hasPermission(Application_Model_Entity_Entity_Permissions::RESERVE_ACCOUNT_VENDOR_VIEW)): ?>
            <?php echo $this->setButtons(array('reserve-accounts-vendor'),$entityId);?>
        <?php endif ?>
        <?php if (!$vendor->hasDeductions() && !$vendor->hasTransactions() && Application_Model_Entity_Accounts_User::getCurrentUser()->hasPermission(Application_Model_Entity_Entity_Permissions::VENDOR_MANAGE)) : ?>
            <a class="btn btn-danger confirm pull-right" confirm-type="Deletion" href="<?php echo $this->url(array('action' => 'delete', 'controller' => 'vendors_index', 'id' => $vendor->getId()), null, true)?>"><i class="icon-trash icon-white"></i> Delete Vendor</a>
        <?php endif ?>
    </div>
    <?php else: ?>
    <h3>Create Vendor</h3><br />
    <div class="left bank-reserve-acc-actions">
        <a class="btn btn-primary disabled" href="#"><i class="icon-pencil icon-white"></i>Reserve Accounts</a>
    </div>
    <?php endif ?>

<form  action="<?php echo $this->escape($this->form->getAction()); ?>"
       method="<?php echo $this->escape($this->form->getMethod()); ?>"
       name="<?php echo $this->escape($this->form->getName()) ?>"
       class="form-horizontal<?php echo ($this->form->id->getValue()) ? ' hide-buttons': '' ?>">
    <?php echo $this->form->id; ?>
    <?php echo $this->form->entity_id; ?>

    <div class="row">
        <div class="span7">
            <?php echo $this->form->code; ?>
            <?php echo $this->form->name; ?>
            <?php echo $this->form->tax_id; ?>
        </div>
    </div>

    <div class="form-actions">
        <?php if (isset($this->form->submit)): ?>
            <input type="submit" name="submit" id="submit" value="Save" class="btn btn-primary">
        <?php endif ?>
        <a class="btn cancel btn-danger" <?php echo $this->cancelUrl ?>>Cancel</a>
    </div>
</form>


<div id="confirm-modal" class="modal hide fade in">
    <div class="modal-header">
        <a class="btn close" data-dismiss="modal">X</a>
        <h3>Confirm <span class="confirm-type"></span> of Records</h3>
    </div>
    <div class="modal-body">
        <p class="confirm-description"><span class="confirm-type"></span> these records is irreversible.</p>
        <p>Do you want to proceed?</p>
    </div>
    <div class="modal-footer">
        <a href="" class="btn btn-danger" id="btn-confirm">Yes</a>
        <a data-dismiss="modal" class="btn btn-success">No</a>
    </div>
</div>
