FROM nginx:latest

# install node and npm
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# Copy vhost
COPY ./docker/azure/nginx/vhost.conf /etc/nginx/templates/default.conf.template

# Copy app data
COPY . /var/www/html

WORKDIR /var/www/html

RUN npm i && \
    npm run build
